# https://github.com/probot/settings

branches:
    - name: master
      protection:
          enforce_admins: false
          required_pull_request_reviews:
              dismiss_stale_reviews: true
              require_code_owner_reviews: true
              required_approving_review_count: 1
          required_status_checks:
              contexts:
                  -  "Grumphp"
              strict: false
          restrictions: null

labels:
    - name: bug
      color: ee0701

    - name: dependencies
      color: 0366d6

    - name: enhancement
      color: 0e8a16

    - name: question
      color: cc317c

    - name: security
      color: ee0701

    - name: stale
      color: eeeeee

repository:
    allow_merge_commit: true
    allow_rebase_merge: true
    allow_squash_merge: true
    default_branch: master
    description: "Adds a specific header to every response to disable Google's usage of your site in it's FLoC tracking method."
    homepage: https://github.com/loophp/go-unfloc-yourself-bundle
    topics: floc,ad,tracking,google
    has_downloads: true
    has_issues: true
    has_pages: false
    has_projects: false
    has_wiki: false
    name: go-unfloc-yourself-bundle
    private: false
